# Server 1
server {
    listen 8080;
    server_name example.com www.example.com;
    root /var/www/site1;
    # Default error pages
    error_page 404 /errors/404.html;
    error_page 500 /errors/500.html;
    # Max client body size
    client_max_body_size 1048576; # 1MB
    # Root location /
    location / {
        index index.html index.php;
        autoindex off;
        limit_except GET POST;
    }
    # Admin panel
    location /admin {
        root /var/www/admin;
        index admin.html;
        autoindex on; #Server dynamically generates an HTML page listing the directory contents
        limit_except GET;
    }
    # File uploads
    location /upload {
        root /var/www/uploads;
        upload on;
        upload_path /var/www/uploads/files;
        limit_except POST;
    }
    # Redirection
    location /old {
        return 301 /new;
    }
}
# Server 2
server {
    listen 8000;
    server_name test.local localhost;
    root /var/www/site2;
    location / {
        index main.html;
        autoindex off;
        limit_except GET;
    }
    location /images {
        root /var/www/media;
        index index.html index.htm;
        autoindex on;
        limit_except GET;
    }
}
# Server 3 (minimal/base case)
server {
    listen 9000;
    server_name minimal.local;
    root /var/www/minimal;
    # No locations specified — all defaults
    # Default index file: index.html
    # Default autoindex: off
    # Allowed methods: GET
}

# if all locations has a root defined the server can exist without a root defined
# you can write limit_except GET GET; , cus nginx allow duplication it will be stored only once
# you can write index index.x index.x; , cus nginx allow duplication but it will be stored only once
# you can write server_name minimal.local minimal.local; , cus nginx allow duplication but it will be stored only once
# autoindex on; #Server dynamically generates an HTML page listing the directory contents if not exist
# for index 'index index.html index.htm;' order matters , you show the first one that exist in the folder

