server
{
    listen 80;
    listen 90;
    listen 0.0.0.1:8080;
    server_name example.com;
    root /var/www/example;
    location /1
    {
        
    }
}

server
{
    listen 80;
    listen 90;
    listen 0.0.0.1:8080;
    server_name unexisting;
    root /var/www/unexisting;
    location /1
    {
    }
}