server {
    listen 80;
    server_name example.com;
    root /var/www/example;
}

server {
    listen 80;
    server_name blog.com;
    root /var/www/blog;
}

server {
    listen 80;
    server_name shop.com hello.pol;
    root /var/www/shop;
}

