

server {
    listen 1025;
	listen 1026;
	server_name localhost;
	root ./www1;
	# index index.htm;
	autoindex on;
	client_max_body_size 2k;

	# keep_alive_timeout 20;
	# client_read_timeout 600;

	location / {
		method GET POST DELETE;
		upload_store ./www1/uploads;
		index index.htm;
		cgi_ext .py;
		cgi_path /bin/python3;
	}
	location /upload{
		method DELETE POST;
		# delete_files on;
	}
	location /get-only {
		method GET;
	}
	location /post-only {
		method POST;
	}
	location /old-page {
       return 301 /new-page;
    }
	location /temp-page {
		return 302 /index.htm;
	}
	location /ext-redirect {
		return 301 http://example.com;
	}

	location /autoindex-dir {
		autoindex  on;
	}
	
	location /no-index-dir {
		autoindex  off;
	}

	location /empty_dir {
		autoindex  off;
	}

	location /auto-with-index {
		autoindex  on;
		index      index.htm;
	}

	location /mapped {
		root ./www1/root-Test;
    	index index.htm;
	}
	location /dir-with-index { 
		root ./www1;
		index index.htm;
	}
	location /cgi-bin {
		cgi_ext .py;
        cgi_path /bin/python3;
		method POST GET;
	}

}



server {
    listen localhost:1027;
    server_name localhost;
    root ./www/html;

    location / {
        method GET;
        index index.html;
    }

    location /post_body {
        method POST;
        client_max_body_size 100;
    }

    location /directory {
		method GET POST DELETE;
        root ./YoupiBanane;
        index youpi.bad_extension;
        autoindex on;
        cgi_ext .bla;
        cgi_path ./tests/cgi_test;
		cgi_timeout 120s;
        client_max_body_size 100g;
    }

    location /directory/Yeah {
        method GET;
        root ./YoupiBanane/Yeah;
        index youpi.bad_extension;
        autoindex off;
    }
}

# HEAD / HTTP/1.1
# Host: localhost:1027