server {
    listen localhost:8080;
    server_name localhost;
    root ./www/html;

    location /
    {
        method GET;
        cgi_ext .bla;
        cgi_path ./tests/cgi_ext;
    }

    location /post_body
    {
        client_max_body_size 100;
    }

    # loctine /path/    ! is valid
    location /directory/
    {        
        root ./YoupiBanane;
        method GET;
        index youpi.bad_extension;
    }
    location /directory/Yeah/
    {        
        root ./YoupiBanane;
        method GET;
        index youpi.bad_extension;
    }

}
