server {
    listen 8080;
    server_name localhost;
    root ./www/html;
    error_page 404 /errors/404.html;
    client_max_body_size 10m;

    location / {
        method GET POST;
        index index.html;
        autoindex off;
    }

    location /upload {
        method GET POST DELETE;
        upload_store ./www/uploads;
        autoindex on;
    }

    location /cgi-bin {
        method GET POST;
        root ./www;
        cgi_ext .py .sh;
        cgi_path /usr/bin/python3;
    }

    location /redirect {
        return 301 http://localhost:8080/;
    }
}

server {
    listen 8081;
    server_name localhost;
    root ./www/html;
    error_page 404 /errors/404.html;
    client_max_body_size 5m;

    location / {
        method GET;
        index index.html;
        autoindex off;
    }
}
